version: '1'
services:

    local.storage.emulator:
        image: "mcr.microsoft.com/azure-storage/azurite:latest"
        container_name: local.storage.emulator
        ports:
            - 10000:10000
            - 10001:10001